default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-yaml
        exclude: ^chart/
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ^(docs/|gdocs/)
    -   id: pretty-format-json
        args: ['--autofix']
        exclude: .ipynb
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        exclude: ^(docs/|gdocs/)
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^(docs/|gdocs/)
    -   id: check-added-large-files
        args: ['--maxkb=500']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.12b0]
-   repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["--skip-editable"]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
