default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
        exclude: ^chart/
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ^(docs/|gdocs/)
    -   id: pretty-format-json
        args: ['--autofix']
        exclude: .ipynb
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        exclude: ^(docs/|gdocs/)
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^(docs/|gdocs/)
    -   id: check-added-large-files
        args: ['--maxkb=3000']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==26.5.1]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
