sonar.projectKey=p16-shapash
sonar.projectName=shapash
sonar.sourceEncoding=UTF-8

sonar.sources=shapash
sonar.tests=tests
sonar.exclusions=tests/**,tutorial/**,docs/**

sonar.python.version=3.11,3.12,3.13,3.14
